apiVersion: config.istio.io/v1alpha2
kind: quota
metadata:
  name: requestcount
  namespace: istio-config-default
spec:
  dimensions:
    source: request.headers["x-forwarded-for"] | "unknown"
    response: response.code
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: quota
  namespace: istio-config-default
spec:
  match: response.code==404
  actions:
  - handler: handler.memquota
    instances:
    - requestcount.quota
